---
- hosts: 
  serial: 10
  user: username
  vars:
    - ansible_ssh_user: "username"
    - user_password: "Password"
  tasks:
  - name: Change User Password For One From Vars File
    shell: echo "{{ user_password }}" | sudo passwd --stdin username
    no_log: True
