---
- hosts: root-change
  user: username
  vars:
    - ansible_ssh_user: "username"
  tasks:
  - name: Change Root Password For One From Vars File (In Inventory File!)
    shell: echo "{{ root_password }}" | sudo passwd --stdin root
    no_log: True
