version: '2'
services:
  web:
    image: httpd:2.4.32
    ports:
     - "0:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs-example
        awslogs-region: eu-west-2
        awslogs-stream-prefix: example
      
